import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "@fontsource/work-sans/latin.css";
import "bootstrap/dist/css/bootstrap.css";

import "./globals.scss";
import Footer from "../Components/shared/footer";
import Layout from "../Components/Layout/Layout";
import Header from "../Components/shared/header";
import Script from "next/script";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  display: "swap",
});
const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: { default: "Plutohub", template: "%s - Plutohub" },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${interSans.variable} ${plusJakartaSans.variable}`}
    >
      <head>
        {/* Google Site Verification */}
        <meta
          name='google-site-verification'
          content='jL50bNw8bkBkNtudsNvptQ0motABgDg2_kSDEylPrxk'
        />
      </head>
      <body>
        {/* Google Analytics */}
        <Script
          src='https://www.googletagmanager.com/gtag/js?id=G-BV2Q0LTKVM'
          strategy='afterInteractive'
        />
        <Script id='google-analytics' strategy='afterInteractive'>
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-BV2Q0LTKVM');
          `}
        </Script>
        <Layout>
          <Header />
          {children}
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
